<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
* Implements hook_ENTITY_TYPE_view() for node entities.
*/
function body_trimming_node_view(array &$build, EntityInterface $node, EntityViewDisplayInterface $display, $view_mode) {
  if ($view_mode == 'teaser') {
    $body = $build['body'][0]['#text'];
    if (strlen($body) > 150) {
      $build['body'][0]['#text'] = substr($body, 0, 147) . '...';
    }
  }
}